package schema

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

const seasonPreflightDDL = `
CREATE TABLE IF NOT EXISTS users (
	id text PRIMARY KEY,
	username text NOT NULL UNIQUE,
	password_hash text NOT NULL,
	is_admin boolean NOT NULL DEFAULT false,
	must_change_password boolean NOT NULL DEFAULT false,
	password_changed_at timestamptz,
	created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sectors (
	id integer PRIMARY KEY,
	name text NOT NULL,
	is_protectorate boolean NOT NULL DEFAULT false,
	protectorate_fighters integer NOT NULL DEFAULT 0,
	created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seasons (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL,
	started_at timestamptz NOT NULL DEFAULT now(),
	ended_at timestamptz,
	active boolean NOT NULL DEFAULT true
);

INSERT INTO seasons(name, active)
SELECT 'Season 1', true
WHERE NOT EXISTS (SELECT 1 FROM seasons);

CREATE TABLE IF NOT EXISTS players (
	id text PRIMARY KEY,
	user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	credits bigint NOT NULL DEFAULT 0,
	xp bigint NOT NULL DEFAULT 0,
	level integer NOT NULL DEFAULT 1,
	ship_type text NOT NULL DEFAULT 'SCOUT',
	ship_cargo_upgrades integer NOT NULL DEFAULT 0,
	ship_turn_upgrades integer NOT NULL DEFAULT 0,
	turns integer NOT NULL DEFAULT 0,
	turns_max integer NOT NULL DEFAULT 100,
	sector_id integer NOT NULL REFERENCES sectors(id),
	cargo_max integer NOT NULL DEFAULT 30,
	cargo_ore integer NOT NULL DEFAULT 0,
	cargo_organics integer NOT NULL DEFAULT 0,
	cargo_equipment integer NOT NULL DEFAULT 0,
	last_turn_regen timestamptz NOT NULL DEFAULT now(),
	season_id integer REFERENCES seasons(id),
	created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE players
	ADD COLUMN IF NOT EXISTS season_id integer REFERENCES seasons(id);

UPDATE players
SET season_id = (SELECT id FROM seasons WHERE active=true ORDER BY id DESC LIMIT 1)
WHERE season_id IS NULL;

ALTER TABLE players
	ALTER COLUMN season_id SET NOT NULL;

CREATE TABLE IF NOT EXISTS admin_audit_log (
	id bigserial PRIMARY KEY,
	actor_user_id text REFERENCES users(id) ON DELETE SET NULL,
	action text NOT NULL,
	details jsonb NOT NULL DEFAULT '{}'::jsonb,
	created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created_at
	ON admin_audit_log(created_at DESC);
`

// PrepareSeasonSchema establishes prerequisite tables and columns before the
// legacy DDL creates dependent indexes. It is safe on fresh and existing data.
func PrepareSeasonSchema(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx, seasonPreflightDDL)
	return err
}
