package schema

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

const ddl = `
CREATE TABLE IF NOT EXISTS users (
	id text PRIMARY KEY,
	username text NOT NULL UNIQUE,
	password_hash text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sectors (
	id integer PRIMARY KEY,
	name text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS warps (
	from_sector integer NOT NULL REFERENCES sectors(id) ON DELETE CASCADE,
	to_sector integer NOT NULL REFERENCES sectors(id) ON DELETE CASCADE,
	one_way boolean NOT NULL DEFAULT false,
	PRIMARY KEY (from_sector, to_sector)
);

CREATE TABLE IF NOT EXISTS ports (
	sector_id integer PRIMARY KEY REFERENCES sectors(id) ON DELETE CASCADE,

	ore_mode text NOT NULL,
	ore_qty integer NOT NULL,
	ore_base_qty integer NOT NULL,
	ore_base_price integer NOT NULL,
	ore_regen integer NOT NULL,

	organics_mode text NOT NULL,
	organics_qty integer NOT NULL,
	organics_base_qty integer NOT NULL,
	organics_base_price integer NOT NULL,
	organics_regen integer NOT NULL,

	equipment_mode text NOT NULL,
	equipment_qty integer NOT NULL,
	equipment_base_qty integer NOT NULL,
	equipment_base_price integer NOT NULL,
	equipment_regen integer NOT NULL
);

CREATE TABLE IF NOT EXISTS players (
	id text PRIMARY KEY,
	user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	credits bigint NOT NULL DEFAULT 0,
	turns integer NOT NULL DEFAULT 0,
	turns_max integer NOT NULL DEFAULT 100,
	sector_id integer NOT NULL REFERENCES sectors(id),
	cargo_max integer NOT NULL DEFAULT 30,
	cargo_ore integer NOT NULL DEFAULT 0,
	cargo_organics integer NOT NULL DEFAULT 0,
	cargo_equipment integer NOT NULL DEFAULT 0,
	last_turn_regen timestamptz NOT NULL DEFAULT now(),
	created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_players_user_id ON players(user_id);
CREATE INDEX IF NOT EXISTS idx_players_sector_id ON players(sector_id);

CREATE TABLE IF NOT EXISTS player_discoveries (
	player_id text NOT NULL REFERENCES players(id) ON DELETE CASCADE,
	sector_id integer NOT NULL REFERENCES sectors(id) ON DELETE CASCADE,
	discovered_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (player_id, sector_id)
);

CREATE TABLE IF NOT EXISTS logs (
	id bigserial PRIMARY KEY,
	player_id text NOT NULL REFERENCES players(id) ON DELETE CASCADE,
	created_at timestamptz NOT NULL DEFAULT now(),
	kind text NOT NULL,
	message text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_logs_player_id_created_at ON logs(player_id, created_at DESC);

-- Phase 2: seasons
CREATE TABLE IF NOT EXISTS seasons (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL,
	started_at timestamptz NOT NULL DEFAULT now(),
	ended_at timestamptz,
	active boolean NOT NULL DEFAULT true
);

INSERT INTO seasons(name, active)
SELECT 'Season 1', true
WHERE NOT EXISTS (SELECT 1 FROM seasons);

ALTER TABLE players
	ADD COLUMN IF NOT EXISTS season_id integer REFERENCES seasons(id);

UPDATE players
SET season_id = (SELECT id FROM seasons WHERE active=true ORDER BY id DESC LIMIT 1)
WHERE season_id IS NULL;

ALTER TABLE players
	ALTER COLUMN season_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_players_season_id ON players(season_id);

-- Phase 2: corporations
CREATE TABLE IF NOT EXISTS corporations (
	id text PRIMARY KEY,
	name text NOT NULL UNIQUE,
	credits bigint NOT NULL DEFAULT 0,
	created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_corporations_name_ci ON corporations (lower(name));

CREATE TABLE IF NOT EXISTS corp_members (
	corp_id text NOT NULL REFERENCES corporations(id) ON DELETE CASCADE,
	player_id text NOT NULL REFERENCES players(id) ON DELETE CASCADE,
	role text NOT NULL DEFAULT 'MEMBER',
	joined_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (corp_id, player_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_corp_members_player_id ON corp_members(player_id);
CREATE INDEX IF NOT EXISTS idx_corp_members_corp_id ON corp_members(corp_id);

CREATE TABLE IF NOT EXISTS corp_messages (
	id bigserial PRIMARY KEY,
	corp_id text NOT NULL REFERENCES corporations(id) ON DELETE CASCADE,
	player_id text NOT NULL REFERENCES players(id) ON DELETE CASCADE,
	created_at timestamptz NOT NULL DEFAULT now(),
	message text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_corp_messages_corp_id_created_at ON corp_messages(corp_id, created_at DESC);

-- Phase 2: planets
CREATE TABLE IF NOT EXISTS planets (
	id bigserial PRIMARY KEY,
	sector_id integer NOT NULL UNIQUE REFERENCES sectors(id) ON DELETE CASCADE,
	name text NOT NULL,
	owner_player_id text REFERENCES players(id) ON DELETE SET NULL,
	owner_corp_id text REFERENCES corporations(id) ON DELETE SET NULL,
	production_ore integer NOT NULL DEFAULT 0,
	production_organics integer NOT NULL DEFAULT 0,
	production_equipment integer NOT NULL DEFAULT 0,
	storage_ore integer NOT NULL DEFAULT 0,
	storage_organics integer NOT NULL DEFAULT 0,
	storage_equipment integer NOT NULL DEFAULT 0,
	storage_max integer NOT NULL DEFAULT 1000,
	citadel_level integer NOT NULL DEFAULT 0,
	last_produced timestamptz NOT NULL DEFAULT now(),
	created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_planets_sector_id ON planets(sector_id);
CREATE INDEX IF NOT EXISTS idx_planets_owner_player_id ON planets(owner_player_id);
CREATE INDEX IF NOT EXISTS idx_planets_owner_corp_id ON planets(owner_corp_id);

-- Phase 2: mines
CREATE TABLE IF NOT EXISTS mines (
	sector_id integer NOT NULL REFERENCES sectors(id) ON DELETE CASCADE,
	owner_player_id text NOT NULL REFERENCES players(id) ON DELETE CASCADE,
	owner_corp_id text REFERENCES corporations(id) ON DELETE SET NULL,
	qty integer NOT NULL DEFAULT 0,
	created_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (sector_id, owner_player_id)
);

CREATE INDEX IF NOT EXISTS idx_mines_sector_id ON mines(sector_id);

-- Phase 3: per-player scan intel (ports)
CREATE TABLE IF NOT EXISTS player_sector_intel (
	player_id text NOT NULL REFERENCES players(id) ON DELETE CASCADE,
	sector_id integer NOT NULL REFERENCES sectors(id) ON DELETE CASCADE,
	scanned_at timestamptz NOT NULL DEFAULT now(),

	ore_mode text NOT NULL,
	ore_qty integer NOT NULL,
	ore_base_qty integer NOT NULL,
	ore_price integer NOT NULL,

	organics_mode text NOT NULL,
	organics_qty integer NOT NULL,
	organics_base_qty integer NOT NULL,
	organics_price integer NOT NULL,

	equipment_mode text NOT NULL,
	equipment_qty integer NOT NULL,
	equipment_base_qty integer NOT NULL,
	equipment_price integer NOT NULL,

	PRIMARY KEY (player_id, sector_id)
);

CREATE INDEX IF NOT EXISTS idx_player_sector_intel_player_id_scanned_at ON player_sector_intel(player_id, scanned_at DESC);
CREATE INDEX IF NOT EXISTS idx_player_sector_intel_sector_id ON player_sector_intel(sector_id);

-- Phase 3: scheduled events (anomalies, invasions, limited-time sectors)
CREATE TABLE IF NOT EXISTS events (
	id bigserial PRIMARY KEY,
	kind text NOT NULL,
	sector_id integer NOT NULL REFERENCES sectors(id) ON DELETE CASCADE,
	commodity text NOT NULL DEFAULT 'ALL',
	price_percent integer NOT NULL DEFAULT 100,
	severity integer NOT NULL DEFAULT 1,
	title text NOT NULL,
	description text NOT NULL,
	started_at timestamptz NOT NULL DEFAULT now(),
	ends_at timestamptz NOT NULL,
	active boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_events_active_ends_at ON events(active, ends_at);
CREATE INDEX IF NOT EXISTS idx_events_sector_id ON events(sector_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_events_active_sector ON events(sector_id) WHERE active=true;
`

func Ensure(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx, ddl)
	return err
}
